### ISSUE TITLE
Missing Index.js

### ISSUE THREAD

**Issue by NitroNaut09** [Bergbok/Spicetify-Creations#14] opened 2024-12-23 10:26 UTC
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.2.50.335.g5e2860a8 (Flatpak)
- Spicetify version: 2.38.7

Linux Fedora 41/GNOME 47
```

### 📝 Description

Well, Spicetify throws an error saying there's no index.js & Spotify opens, throws a blank black screen. That's it nothing else. All extensions and apps are fine, just: History, and Playlist Tags

**Comment by Bergbok** [comment] 2024-12-23 10:31
Duplicate of https://github.com/Bergbok/Spicetify-Creations/issues/7

Typically a installation problem.

Double check that you followed the [installation instructions](https://github.com/Bergbok/Spicetify-Creations/tree/main/CustomApps/playlist-tags#installation).

**Closed as completed by Bergbok** 2024-12-23 10:31 UTC
